#!/usr/bin/env php
<?php

declare(strict_types=1);

defined('YII_DEBUG') or define('YII_DEBUG', true);

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

Yii::setAlias('@console', __DIR__ . '/console');
Yii::setAlias('@common', __DIR__ . '/common');
Yii::setAlias('@api', __DIR__ . '/api');
Yii::setAlias('@frontend', __DIR__ . '/frontend');

$config = require __DIR__ . '/console/config/main.php';

$application = new yii\console\Application($config);

exit($application->run());
